### ISSUE TITLE
f3d model

### ISSUE THREAD

**Issue by DaniilMaximov** [compressionKeyboards/compression4c#1]
![image](https://github.com/compressionKeyboards/compression4c/assets/90193751/2d0c3483-c9ad-47b6-be28-5be18cc07f80)

Hi, you have succeeded in creating a very cool keyboard! I use it every day at the moment.
But I'm also using a special magnetic connector and because of that I won't be able to use the travel case. Would you be able to send me the source files in f3d or step format? I also want to modify the keyboard body a bit.
I would be very grateful!

**Comment by bennetthermanoff** [comment]
Absolutely. Shoot me a message on the discord: https://discord.gg/MjRrj3Cn

**Comment by bennetthermanoff** [comment]
[Case.zip](https://github.com/compressionKeyboards/compression4c/files/14651487/Case.zip)

**Comment by bennetthermanoff** [comment]
Looks like an amazing build! Love the wired version.

**Comment by DaniilMaximov** [comment]
Thank u so much!

**Comment by RichardFevrier** [comment]
Hi 👋 was it necessary to modify the pcb to be non wireless?

**Comment by DaniilMaximov** [comment]
Hi! Yes, but unfortunately I can't find changed files for wierd pcb quickly

**Comment by RichardFevrier** [comment]
I'll be patient 🙂 Thanks already for answering.

The Compression 4c is so great with the case @bennetthermanoff and to my eyes this makes it even better @DaniilMaximov 
Thanks both for your work! 🙏❤️

Now probably stupid questions but:
- using the cabled version removes completely the wireless functionality?
- can the power/data cable be swapped either side or flashing the firmware will be requiered for that matter?

**Comment by DaniilMaximov** [comment]
1. yes - controllers are different. I use Atmega 32U4
2. yes, but u have to change it in firmware
