### ISSUE TITLE
3D files for generic version generator

### ISSUE THREAD

**Issue by BlueDrink9** [compressionKeyboards/compression4c#2]
I love this design. It'd be a shame to confine it to a single board. I'm interested in creating a generator for cases like this. I'm thinking openscad, input an existing stl or maybe even pcb file, and have openscad project the outline then build the case from there. Can't say I'd do it soon, but definitely at some point. I'd be very happy to suggest all donations get forwarded to you. Would you be willing to share the 3D design files, step, or even just dimensions etc to help me create a parametrised port of this?

**Comment by bennetthermanoff** [comment]
Absolutely! shoot me a message on the discord I can get you f3d and step files. https://discord.gg/MjRrj3Cn

**Comment by bennetthermanoff** [comment]
Also no need for donos. A link to this github would be enough :)
